### PR TITLE
Fix HardFault

### LINKED ISSUE #2: HardFault when writing u16
This line in src/ctx/num.rs:80 HardFaults for me:

```rust
unsafe { *(&mut bytes[0] as *mut _ as *mut _) = val };
```

```
     0x0000f3d4 <+168>:   ldrh    r0, [r0, #16]
     0x0000f3d6 <+170>:   rev16   r0, r0
=>   0x0000f3d8 <+172>:   strh    r0, [r6, #4]
```

Register values after `0x0000f3d6` has executed:

```
(gdb) info reg
r0             0x1e00              7680
r1             0x1                 1
r2             0xb                 11
r3             0x74                116
r4             0x11                17
r5             0x75                117
r6             0x2000045f          536872031
r7             0x200067b8          536897464
r8             0x76ffeebf          1996484287
r9             0x200002dc          536871644
r10            0xe9579d7e          -380134018
r11            0xeef7fdfa          -285737478
r12            0xfbdfedbf          -69210689
sp             0x20006690          0x20006690
lr             0x407b              16507
pc             0xf3d8              0xf3d8 <<mqtt_sn::defs::Message as byte::TryWrite>::try_write+172>
xPSR           0x21000017          553648151
msp            0x20006690          0x20006690
psp            0xfffbadf4          0xfffbadf4
primask        0x0                 0
basepri        0x0                 0
faultmask      0x0                 0
control        0x0                 0
```

I have validated that `r6 + 4` is a valid memory address inside of the write buffer. No clue what is going on here.

Target platform is armv6-m, it works fine on Linux (x64).

### PR DESCRIPTION
**Pull request by henrikssn**
I ran the benchmarks vs master and there was no difference (so I assume this compiles down to equivalent code but avoids the unsafe stuff).

Fixes #2

### CODE REVIEW

File: src/ctx/num.rs [hunk 1]
```diff
@@ -57,10 +58,9 @@ macro_rules! num_impl {
             fn try_read(bytes: &'a [u8], endian: Endian) -> Result<(Self, usize)> {
                 check_len(bytes, $size)?;
 
-                let val: $ty = unsafe { *(&bytes[0] as *const _ as *const _) };
                 let val = match endian {
-                    Endian::Big => val.to_be(),
-                    Endian::Little => val.to_le(),
+                    Endian::Big => <$ty>::from_be_bytes(bytes[..$size].try_into().unwrap()),
+                    Endian::Little => <$ty>::from_le_bytes(bytes[..$size].try_into().unwrap()),
```
Comment (andylokandy) [inline src/ctx/num.rs:63]:
```suggestion
                    Endian::Big => <$ty>::from_be_bytes(bytes[..$size].try_into()?),
                    Endian::Little => <$ty>::from_le_bytes(bytes[..$size].try_into()?),
```

**Review by andylokandy — COMMENTED** [review]
Thank you! I've some small suggestions, other's LGTM.

File: src/ctx/num.rs (hunk 1 above)
Comment (henrikssn) [reply src/ctx/num.rs]: Removed usages of unwrap

**Comment by andylokandy** [comment]
@henrikssn Thank you!
